# Generated by Django 4.1 on 2022-09-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_age', models.IntegerField(default=0)),
                ('emp_number', models.IntegerField(default=0)),
                ('emp_address', models.CharField(max_length=200)),
            ],
        ),
    ]
