# Generated by Django 4.1 on 2022-09-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restBasicsApp', '0004_rename_myuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
