# Generated by Django 4.1 on 2022-09-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restBasicsApp', '0005_rename_user_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
    ]
